Repository AvodaAI/Frontend, pull requests merged in 2024-12, with the labels that each got.

#52 Feature/invitaions
  src/app/(auth)/employees/components/AddEmployeeForm.tsx
  src/app/(auth)/invitations/components/invitations-table.tsx
  src/app/(auth)/inviteUser/page.tsx
  src/hooks/useRole.ts
Labels: Review effort [1-5]: 3

#53 Integrated auth apis
  src/app/components/auth/SignIn.tsx
  src/app/components/auth/SignUp.tsx
  src/app/components/layout/Header.tsx
Labels: Review effort [1-5]: 2

#54 Implemented organization feature
  src/app/(auth)/organization/components/AddOrganizationForm.tsx
  src/app/(auth)/organization/components/EditOrganizationModal.tsx
  src/app/(auth)/organization/components/OrganizationTable.tsx
  src/app/(auth)/organization/page.tsx
  src/app/components/layout/Header.tsx
  src/app/page.tsx
  src/types/index.ts
  src/types/organization.ts
Labels: Review effort [1-5]: 4

#55 Displaying navigation routes based on roles
  src/hooks/getLoggedUser.ts
  src/hooks/useRole.ts
Labels: Review effort [1-5]: 3

#56 chore: update eslint configuration with typescript and react plugins
  .eslintrc.json
  pnpm-lock.yaml
  src/app/api/timer/[id]/route.ts
Labels: Review effort [1-5]: 1

#58 Displaying role and name on dashboard
  src/app/(auth)/dashboard/components/userDetails.tsx
  src/app/(auth)/dashboard/page.tsx
  src/app/(auth)/invitations/components/invitations-table.tsx
  src/app/(auth)/inviteUser/page.tsx
  src/app/(auth)/organization/components/AddOrganizationForm.tsx
  src/app/(auth)/organization/components/EditOrganizationModal.tsx
  src/app/(auth)/organization/components/OrganizationTable.tsx
  src/app/(auth)/organization/page.tsx
  src/app/components/auth/SignIn.tsx
  src/hooks/useRole.ts
  src/middleware.ts
  src/utils/fetchWrapper.ts
Labels: Review effort [1-5]: 2
