Repository AvodaAI/Frontend, pull requests merged in 2025-01, with the labels that each got.

#62 Auth pages implemented
  package.json
  pnpm-lock.yaml
  src/app/(Authentication)/forgot-password/page.tsx
  src/app/(Authentication)/layout.tsx
  src/app/(Authentication)/login/page.tsx
  src/app/(Authentication)/reset-password/page.tsx
  src/app/(Authentication)/signup/page.tsx
  src/app/components/auth/otp.tsx
  src/app/components/ui/input-otp.tsx
  src/app/components/ui/input.tsx
  src/app/globals.css
  src/app/login/page.tsx
Labels: Review effort [1-5]: 4

#66 Auth pages
  src/app/(Authentication)/login/page.tsx
  src/app/(Authentication)/signup/page.tsx
Labels: Review effort [1-5]: 3

#71 Refactor authentication pages for improved readability and consistency
  src/app/(Authentication)/login/page.tsx
  src/app/(Authentication)/reset-password/page.tsx
  src/app/(Authentication)/signup/page.tsx
  src/app/org/[id]/(auth)/invitations/components/InviteEmployeeForm.tsx
  src/app/org/[id]/(auth)/inviteUser/page.tsx
  src/app/org/[id]/(auth)/time-logs/page.tsx
Labels: Review effort [1-5]: 4

#72 Av 146 create UI for create update delete and view tasks
  src/app/components/layout/Header.tsx
  src/app/org/[id]/(auth)/projects/components/ProjectTable.tsx
  src/app/org/[id]/(auth)/tasks/components/TaskForm.tsx
  src/app/org/[id]/(auth)/tasks/components/TaskTable.tsx
  src/app/org/[id]/(auth)/tasks/page.tsx
  src/app/org/page.tsx
  src/types/task.ts
  src/utils/services/taskServices.ts
  src/utils/timeFormatHandler.ts
Labels: Review effort [1-5]: 4

#73 closed AV-29
  src/app/components/layout/Header.tsx
  src/app/org/[id]/(auth)/assigned-task/components/AssignedTasksTable.tsx
  src/app/org/[id]/(auth)/assigned-task/page.tsx
  src/utils/services/taskServices.ts
Labels: Review effort [1-5]: 2

#76 Closed AV-153
  src/app/inviteUser/page.tsx
  src/app/org/[id]/(auth)/invitations/components/InviteEmployeeForm.tsx
  src/app/org/[id]/(auth)/invitations/components/invitations-table.tsx
  src/types/supabase.ts
  src/utils/passwordValidation.ts
  src/utils/user-permission.ts
Labels: Review effort [1-5]: 3

#77 Closed AV-155
  src/app/org/[id]/(auth)/time-tracking/page.tsx
  src/utils/timeFormatHandler.ts
Labels: Review effort [1-5]: 3

#79 Closed AV-156
  src/app/components/layout/Header.tsx
  src/app/org/[id]/(auth)/time-tracking/page.tsx
Labels: Review effort [1-5]: 3

#80 Closed AV-157
  src/app/components/layout/Header.tsx
  src/app/org/[id]/(auth)/manage-permission/components/UpdatePermissionForm.tsx
  src/app/org/[id]/(auth)/manage-permission/page.tsx
  src/types/permission.ts
  src/types/user.ts
  src/utils/constant.ts
  src/utils/services/managePermissionServices.ts
Labels: Review effort [1-5]: 4

#83 Closed AV-158
  src/app/org/[id]/(auth)/invitations/components/InviteEmployeeForm.tsx
Labels: Review effort [1-5]: 3

#84 Closed AV-167
  src/app/inviteUser/page.tsx
  src/app/org/[id]/(auth)/invitations/components/InviteEmployeeForm.tsx
  src/app/org/[id]/(auth)/time-tracking/page.tsx
Labels: Review effort [1-5]: 2

#86 Closed AV-173
  src/app/org/[id]/(auth)/tasks/components/AddTaskForm.tsx
  src/app/org/[id]/(auth)/tasks/components/Tasks.tsx
  src/app/org/[id]/(auth)/tasks/components/columns.tsx
  src/app/org/[id]/(auth)/tasks/modals/AddTaskModal.tsx
  src/lib/formatter.ts
  src/types/task.ts
  src/utils/services/managePermissionServices.ts
  src/utils/services/taskServices.ts
Labels: Review effort [1-5]: 4

#87 Av 40 implement login with google
  public/assets/google-logo.png
  src/app/components/auth/AuthWrapper.tsx
  src/app/components/auth/SignIn.tsx
  src/app/components/layout/Header.tsx
  src/app/page.tsx
  src/utils/services/authServices.ts
Labels: Review effort [1-5]: 3

#88 fix: user permission
  src/hooks/useRole.ts
Labels: Review effort [1-5]: 2
